cache: apt
sudo: false

language: python
python:
  - "3.5"
  - "3.6"
    #  - "3.7"
  - "3.8"
  - "3.9"

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev

notifications:
  email: false

# blocklist
# Block all /*feature*/ branches
# Anything within /_>/ is treated as a Regex
#branches:
#  except:
#  - /*feature*/

# safelist
# Only Build and Test changes of the master and develop branches
branches:
  only:
  - master
  - develop

before_install:
 - travis_retry wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH=/home/travis/miniconda/bin:$PATH
 - conda update --yes conda

install:
 - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
 - source activate test
 - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then conda install --yes nomkl; fi
 - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib seaborn pip nose
 - conda install --yes -c conda-forge python=$TRAVIS_PYTHON_VERSION cvxpy
 - conda install --yes tensorflow=1.15.2 pymanopt
 - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pip install -U numpy; fi
 - pip install setuptools coveralls
 - python setup.py install

script: coverage run test.py tests/*

after_success:
 coveralls
