name: equadratures

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy scipy matplotlib seaborn pip nose cvxpy setuptools coveralls numexpr
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python setup.py install
      - name: Install additional dependencies
        if:  ${{ matrix.python-version != '3.8' && matrix.python-version != '3.9' }}
        run: |
          python -m pip install tensorflow==1.15.2 pymanopt
      - name: Test
        run: |
          coverage run test.py tests/*
          coveralls